### PR TITLE
Keep last frame on animation end

### PR DESCRIPTION
**Pull request by thearaks**

### CODE REVIEW

**Comment by sahasbhop** [comment]
I think it might be better to provide the way a caller can choose whether to display the first frame or the last frame when the animation is finished.

**Comment by thearaks** [comment]
Hi @sahasbhop!
I updated this PR following your suggestion,
I hope it's ok now! :)

**Comment by sahasbhop** [comment]
Hi @thearaks, it's okay now. Thanks a lot :]

**Comment by thearaks** [comment]
@sahasbhop Thank you for this awesome library! :)

**Pull request merged**
